### ISSUE TITLE
Question about resistors.

### ISSUE THREAD

**Issue by NeidalMcCanuk** [juani13973/pedalinio-18-footswitches-prototype#3]
Hello and good night!

Hello juanni13973, my name is Daniel, and I'm very impressed about your project, I don't know many about electronic, and your PedalinoMini Prototype is very clear, but, I have some questions that I hope you can solve me, please.

1) The 3 resistors in the footswitchs boards, are they all from 10 KOhms?
2) The 6 resistors in the bottom in the mainboard, are they from 10 KOhms?
3) The resistors R7 and R8, what about they? Are the 10KOhms too?
4) About the footswitch boards. Excuse my ignorance please... I understand that for every FSx from the mainboard, there are 2 footswitch boards to complete the ladder of 6 switches, ok. Can you explain me how to link the 1st to the 2nd footswitchboard? I can't figure.

Thanks in advance!!

**Comment by juani13973** [comment]
Hi Daniel,
Thx for contacting me and your comments. Let me answer the questions below :

1. The 3 resistors in the footswitchs boards, are they all from 10 KOhms?
No not at all, they are all different building a resistors ladder of 6 footswiches. If you open the Fusion 360 file you will see the values. Or if you go to the pedalino project, you will see a ladder of 5 footswitches. I added 1 more with a 6K8ohms resistor.

2. The 6 resistors in the bottom in the mainboard, are they from 10 KOhms?
Yes all the ones that are below the ESP32 are all 10K (again, did you download the diagrams from alf45tar ? - took them from the project itself)

3. The resistors R7 and R8, what about they? Are the 10KOhms too?
Nop, they are 3K3 Ohms. (Again look at the diagram in alf45tar page or open my fusion 360 file and you will have them all there).

4. About the footswitch boards. Excuse my ignorance please... I understand that for every FSx from the mainboard, there are 2 footswitch boards to complete the ladder of 6 switches, ok. Can you explain me how to link the 1st to the 2nd footswitchboard? I can't figure.
Correct. I wanted to build one PCB board with 6 foot-switches but I had to pay for a full license of Fusion 360, so I had to split the PCB in 2 parts. Each ladder has 3 + 3 foot-switches in 2 different boards.
Look at this diagram, I hope it is clear…..

Juan,

**Comment by juani13973** [comment]
Hi Daniel,
Thx for contacting me and your comments. Let me answer the questions below :

1. The 3 resistors in the footswitchs boards, are they all from 10 KOhms?
No not at all, they are all different building a resistors ladder of 6 footswiches. If you open the Fusion 360 file you will see the values. Or if you go to the pedalino project, you will see a ladder of 5 footswitches. I added 1 more with a 6K8ohms resistor. [look at the picture](https://github.com/juani13973/pedalinio-18-footswitches-prototype/blob/main/images/Ladder%20values.jpg)

2. The 6 resistors in the bottom in the mainboard, are they from 10 KOhms?
Yes all the ones that are below the ESP32 are all 10K (again, did you download the diagrams from alf45tar ? - took them from the project itself)

3. The resistors R7 and R8, what about they? Are the 10KOhms too?
Nop, they are 3K3 Ohms. (Again look at the diagram in alf45tar page or open my fusion 360 file and you will have them all there).

4. About the footswitch boards. Excuse my ignorance please... I understand that for every FSx from the mainboard, there are 2 footswitch boards to complete the ladder of 6 switches, ok. Can you explain me how to link the 1st to the 2nd footswitchboard? I can't figure.
Correct. I wanted to build one PCB board with 6 foot-switches but I had to pay for a full license of Fusion 360, so I had to split the PCB in 2 parts. Each ladder has 3 + 3 foot-switches in 2 different boards.
[Look at this diagram](https://github.com/juani13973/pedalinio-18-footswitches-prototype/blob/main/images/Diagram%20of%20ladder%20and%20PCB.jpeg), I hope it is clear…..

**Comment by NeidalMcCanuk** [comment]
> Hi Daniel,
> Thx for contacting me and your comments. Let me answer the questions below :
> 
> 1. The 3 resistors in the footswitchs boards, are they all from 10 KOhms?
>    No not at all, they are all different building a resistors ladder of 6 footswiches. If you open the Fusion 360 file you will see the values. Or if you go to the pedalino project, you will see a ladder of 5 footswitches. I added 1 more with a 6K8ohms resistor. [look at the picture](https://github.com/juani13973/pedalinio-18-footswitches-prototype/blob/main/images/Ladder%20values.jpg)
> 2. The 6 resistors in the bottom in the mainboard, are they from 10 KOhms?
>    Yes all the ones that are below the ESP32 are all 10K (again, did you download the diagrams from alf45tar ? - took them from the project itself)
> 3. The resistors R7 and R8, what about they? Are the 10KOhms too?
>    Nop, they are 3K3 Ohms. (Again look at the diagram in alf45tar page or open my fusion 360 file and you will have them all there).
> 4. About the footswitch boards. Excuse my ignorance please... I understand that for every FSx from the mainboard, there are 2 footswitch boards to complete the ladder of 6 switches, ok. Can you explain me how to link the 1st to the 2nd footswitchboard? I can't figure.
>    Correct. I wanted to build one PCB board with 6 foot-switches but I had to pay for a full license of Fusion 360, so I had to split the PCB in 2 parts. Each ladder has 3 + 3 foot-switches in 2 different boards.
>    [Look at this diagram](https://github.com/juani13973/pedalinio-18-footswitches-prototype/blob/main/images/Diagram%20of%20ladder%20and%20PCB.jpeg), I hope it is clear…..


Good afternoon!

Oh man! Thanks, I say it before... I'm not a electronic, and I can't figure it this so easy, I think that you use the ladder with 6 witches labeled as "T Helicon Switch 6".

I'll download then a visor or program to see the f3z files content to clarify me more.

Thanks man and excuse me!

**Comment by juani13973** [comment]
Hi Daniel 
No I didn’t use that one.
I use the other one. Look at the diagram… it is not the same
